### PR TITLE
Updated logo

### PR DESCRIPTION
**Pull request by Wolfhound905**
## About this pull request

Since this branch is moving more twoards all interactions I changed the logo.

## Changes

I changed the logo to look like this:

discord-py-interactions</a>

## Checklist

- [x] This is not a code change. (README, docs, etc.)
- [ ] I've run the `pre_push.py` script to format and lint code.
- [ ] I've checked this pull request runs on `Python 3.6.X`.
- [ ] This fixes something in [Issues](https://github.com/eunwoo1104/discord-py-slash-command/issues).
    - Issue:
- [ ] This adds something new.
- [ ] There is/are breaking change(s).
- [ ] (If required) Relevant documentation has been updated/added.

### CODE REVIEW

**Review by benwoo1110 — APPROVED** [review]
🥳

**Comment by LordOfPolls** [comment]
Would that `img_src` even work on pypi?

**Comment by LilSpazJoekp** [comment]
It should. We actually should convert README to rst.

**Comment by i0bs** [comment]
This is closed in favor of #224 recently being merged.

**Pull request closed without merging**
