### PR TITLE
[Addition] Button based embed paginator

### PR DESCRIPTION
**Pull request by JUGADOR123**
## About this pull request

Adds a basic handler for interactive multiple page embeds

## Changes

What changes were made?
 Addition of Paginator.py under utils
## Checklist

- [x] I've run the `pre_push.py` script to format and lint code.
- [ ] I've checked this pull request runs on `Python 3.6.X`.
- [ ] This fixes something in [Issues](https://github.com/eunwoo1104/discord-py-slash-command/issues).
    - Issue:
- [x] This adds something new.
- [ ] There is/are breaking change(s).
- [x] (If required) Relevant documentation has been updated/added.
- [ ] This is not a code change. (README, docs, etc.)

### CODE REVIEW

**Comment by benwoo1110** [comment]
I feel like this should be an example in https://github.com/discord-py-slash-commands/slash-bot where ppl can test out on our server, refer to the code and adapt to their own bot. Shouldn't really be in this lib imo.

**Comment by Catalyst4222** [comment]
There's a paginator for d.py (commands.Paginator). I think it's a good idea to have a button variant instead of the reaction based one, since buttons were partially made as a replacement for reaction menus

**Comment by AstreaTSS** [comment]
> There's a paginator for d.py (commands.Paginator). I think it's a good idea to have a button variant instead of the reaction based one, since buttons were partially made as a replacement for reaction menus

I suppose you could say that. But there's a number of ways of writing a paginator like this - some would inherit from discord.py's pagniator, some would use different labels, etc. That makes establishing a standard much more difficult.

Also consider the fact that the default pagniator (and so, the default help command) does not use reactions at all (at least, I think so - doesn't look like there's any code to handle it). Most reaction-based pagniators are made by other people, and so button-based pagnitors, at least in my opinion, should too.

I think this would be great as a code example, like @benwoo1110 said. But it probably doesn't belong in the library itself.

**Comment by LordOfPolls** [comment]
Not going to rehash what's already been said.

Closing this PR. Feel free to make an example for Slash-Bot

**Pull request closed without merging**
