### PR TITLE
Fix spelling mistakes

### PR DESCRIPTION
**Pull request by LilSpazJoekp**
## About this pull request

This fixes some spelling mistakes.

## Changes

What changes were made?

## Checklist

- [ ] I've checked this pull request runs on `Python 3.6.X`.
- [ ] This fixes something in [Issues](https://github.com/eunwoo1104/discord-py-slash-command/issues).
    - Issue:
- [ ] This adds something new.
- [x] There is/are breaking change(s).
- [ ] (If required) Relavent documentation has been updated/added.
- [x] This is not a code change. (README, docs, etc.)

### CODE REVIEW

**Comment by quirky-bluejay** [comment]
Looks good!
However there are breaking changes because it changes the name of some variables (oops sorry that's probably my fault)

**Comment by LilSpazJoekp** [comment]
Oh yeah you're right! How would you like to handle that?

**Comment by eunwoo1104** [comment]
> Oh yeah you're right! How would you like to handle that?

You can leave previous variable name, then at the docs mark name with spelling mistake as deprecated.

...Or should I request changes about those?

**Comment by LilSpazJoekp** [comment]
@eunwoo1104 Will this work?

**Review by LordOfPolls — APPROVED** [review]

**Review by eunwoo1104 — APPROVED** [review]

**Comment by eunwoo1104** [comment]
Merging this pull request, thank you for contributing!

**Pull request merged**
