### PR TITLE
Fix error when guild id is None.

### LINKED ISSUE #225: Traceback from library on basic function
Traceback on Version 2.0.1. On 1.1.0 working as expected.
python 3.8.5

### Traceback
```
Traceback (most recent call last):
  File "bot.py", line 28, in <module>
    async def purge(ctx, number_of_messages : int):
  File "/home/solumath/.local/lib/python3.8/site-packages/discord_slash/client.py", line 760, in wrapper
    obj = self.add_slash_command(
  File "/home/solumath/.local/lib/python3.8/site-packages/discord_slash/client.py", line 538, in add_slash_command
    if not all(isinstance(item, int) for item in guild_ids):
TypeError: 'NoneType' object is not iterable
```

### Code
```py
@slash.slash(name="purge", description="delete number of messages")
@commands.has_permissions(manage_messages=True)
async def purge(ctx, number_of_messages : int):
    await ctx.channel.purge(limit=number_of_messages)
    await ctx.send("What is real? How do you define real?", delete_after=5)
```
Probably in library as discussed on discord server.

### PR DESCRIPTION
**Pull request by benwoo1110**
## About this pull request

I would say this is quite critical. Not sure why that checking was removed at this commit:
 https://github.com/discord-py-slash-commands/discord-py-interactions/commit/b32d0e2da956bbc31066d7bdbe4240c97258eca3#diff-37afa4fe0663ae6e7e30366179bcffecedbdba72972e291cb682fec2ac4f0a24L538-L539

## Changes

Add checking for when guild_id is None for command.

## Checklist

- [ ] I've run the `pre_push.py` script to format and lint code.
- [ ] I've checked this pull request runs on `Python 3.6.X`.
- [ ] This fixes something in [Issues](https://github.com/eunwoo1104/discord-py-slash-command/issues).
    - Issue: fixes #225
- [ ] This adds something new.
- [ ] There is/are breaking change(s).
- [ ] (If required) Relevant documentation has been updated/added.
- [ ] This is not a code change. (README, docs, etc.)

### CODE REVIEW

**Comment by LilSpazJoekp** [comment]
That was my bad. I thought I added `if guild_ids` to both of those.

**Review by LilSpazJoekp — APPROVED** [review]
LGTM

I missed the other two when I changed that.

**Comment by artem30801** [comment]
It seems to me that with such checks empty list of guild_ids would be a valid input? Is that actually desired? I'm not sure but it could cause some other bugs down the line

**Comment by benwoo1110** [comment]
https://github.com/discord-py-slash-commands/discord-py-interactions/blob/a7f468b66137726a2535a9d62177f6e25a8f8d2f/discord_slash/model.py#L315

It will always be modelled to an empty list from what I can tell.

**Comment by artem30801** [comment]
Then LGTM

**Comment by benwoo1110** [comment]
Actually @artem30801 you are right. There are instances where it tried to .copy a None guild_ids, I think it best is to revert back to what was like before, at least for this hotfix. 

Then we see if we should consider later on whether removing that `guild_ids = guild_ids if guild_ids else []` has any benefit or not. Seen evidently more code change is needed to support it.

**Comment by artem30801** [comment]
I think that
`guild_ids = guild_ids if guild_ids else []`
also could be changed to to
`guild_ids = guild_ids or []`

**Comment by benwoo1110** [comment]
I think both have negligible difference, let keep with what proven works for now. We can do some optimisation on that after this hotfix.

**Review by LordOfPolls — APPROVED** [review]

**Pull request merged**
