### PR TITLE
String Snowflake ID in decorator args

### PR DESCRIPTION
**Pull request by FayeDel**
## About this pull request

This PR essentially warns the user that the command(s) that uses string snowflake IDs as a guild_ids arg does not work and therefore result in "This interaction failed".

## Changes

Added a `guilds_id` check if all of them are ints on both the regular slash client end and on the `cog_ext` end, and provided an Exception upon check failure.

## Checklist

- [X] I've checked this pull request runs on `Python 3.6.X`.
- [X] This fixes something in [Issues](https://github.com/eunwoo1104/discord-py-slash-command/issues).
    - Issue: #129
- [ ] This adds something new.
- [X] There is/are breaking change(s).
- [ ] (If required) Relevant documentation has been updated/added.
- [ ] This is not a code change. (README, docs, etc.)

### CODE REVIEW

**Review by i0bs — APPROVED** [review]

**Review by quirky-bluejay — CHANGES_REQUESTED** [review]
This should raise a custom exception, for example like the others that are in `.error`.
Also not too sure about this one, but shouldn't all development be targeted at the `components` branch?
I wouldn't count this a breaking change as it doesn't 'work' when ids are strings anyways.

**Comment by FayeDel** [comment]
To be completely honest, I wasn't too sure if it would be targeted towards component because I presumed that it was for components and its own spiel. That and, I had to second guess marking if it was a breaking change, but the tip helps in console so I marked it there.

**Comment by LordOfPolls** [comment]
I'm happy with these changes, but can you please make them for the components branch, as per what cat said

**Comment by LordOfPolls** [comment]
Is this complete?

**Comment by FayeDel** [comment]
This is switched to components with its own respective changes, yes. Should have mentioned that earlier, my bad

**Comment by LordOfPolls** [comment]
Please may you run `pre_push.py`, rn your pr is failing due to formatting issues

**Comment by FayeDel** [comment]
Ran the PR and formatted (double checked even without the file and it seems to be fine).

**Review by LordOfPolls — APPROVED** [review]

**Comment by LordOfPolls** [comment]
Merging, thanks for contributing, please dm me on discord for the role

**Review by Toricane — COMMENTED** [review]
test

**Pull request merged**
