### PR TITLE
Permission fixes

### PR DESCRIPTION
**Pull request by benwoo1110**
## About this pull request

Fix some docs and types typo related to the permissions PR.

## Checklist

- [ ] I've checked this pull request runs on `Python 3.6.X`.
- [ ] This fixes something in [Issues](https://github.com/eunwoo1104/discord-py-slash-command/issues).
    - Issue:
- [ ] This adds something new.
- [ ] There is/are breaking change(s).
- [ ] (If required) Relevant documentation has been updated/added.
- [ ] This is not a code change. (README, docs, etc.)

### CODE REVIEW

**Comment by quirky-bluejay** [comment]
Something i was thinking about. Would it be a good idea to document the format of `permissions` for the command decorators?
It's mostly mentioned in getting started, but imo you shouldn't have to look in guides to find that out.

**Comment by benwoo1110** [comment]
Yea the example code should be quite clear that it's a dictionary. Also I improved the docs string for them in the above commit.

Also there is a sentence on it in getting started:
> The key being the guild to apply permissions on, and value being the list of permissions to apply.

**Review by quirky-bluejay — APPROVED** [review]

**Review by LordOfPolls — APPROVED** [review]

**Review by eunwoo1104 — APPROVED** [review]
LGTM

**Comment by eunwoo1104** [comment]
Merging, thank you for contributing!

**Pull request merged**
