### PR TITLE
Make commandObjects inherit from discord.ext.commands

### PR DESCRIPTION
**Pull request by LordOfPolls**
# ===This is not ready for merging===

## About this pull request

Modifies all command objects to inherit from dpy commands ext commands. This allows people to use the decorators and functions provided by command objects

## Changes

- Rebuilt command objects to use `discord.ext.commands.command` as their base
- Added call in `invoke_command` to trigger error decorator if present 

## Checklist

- [x] I've checked this pull request runs on `Python 3.6.X`.
- [ ] This fixes something in [Issues](https://github.com/eunwoo1104/discord-py-slash-command/issues).
    - Issue:
- [x] This adds something new.
- [x] There is/are breaking change(s).
- [ ] (If required) Relavent documentation has been updated/added.
- [ ] This is not a code change. (README, docs, etc.)

## Checklist of functionality
This is a checklist of functionality that has been ported to work with slash command objects. My intent is to get as many of these to work as possible before merging 

- [x] Error decorators
- [x] Cooldown decorators
- [x] Before & after invoke decorators
- [ ] `add_check` method
- [x] `call` method
- [ ] `copy` method
- [x] `get_cooldown_retry_after`
- [x] `reset_cooldown`
- [ ] `update`
- [x] Attributes -- see [dpy](https://discordpy.readthedocs.io/en/latest/ext/commands/api.html#discord.ext.commands.Command)

### CODE REVIEW

**Comment by LordOfPolls** [comment]
Unless I'm missing something, this seems to be working, would appreciate feedback

**Comment by RealCyGuy** [comment]
I tried using this with the newer commits to the main repo (https://github.com/RealCyGuy/discord-py-slash-command/tree/updated-override). When I use command cooldowns, it always raises `CommandOnCooldown` even if it's the first use. I also tried your branch and this happens as well.

**Comment by LordOfPolls** [comment]
I've tried replicating your issue, and it works correctly for me. Can I see your code

**Comment by RealCyGuy** [comment]
This is my command code (in cog):
```py
    @cog_ext.cog_slash(name="compete", description="Compete to earn some bronze medals.", guild_ids=guild_ids)
    @commands.cooldown(1, 20, commands.BucketType.user)
    async def compete(self, ctx: SlashContext):
        # cooldown = self.compete_cooldown.get(str(ctx.author_id), None)
        # now = datetime.now()
        # if cooldown:
        #     difference = now - cooldown
        #     if difference < timedelta(seconds=20):
        #         embed = discord.Embed(title="You are entering competitions too fast!",
        #                               description="Try again in " + str(
        #                                   round((timedelta(seconds=20) - difference).total_seconds())) + " seconds.",
        #                               color=Colours.BRONZE)
        #         return await ctx.send(ctx.author.mention, embed=embed)
        # self.compete_cooldown[str(ctx.author_id)] = now
        embed = discord.Embed(title="Searching for competitions...", description="\u2591" * 10 + " [0.0%]",
                              colour=Colours.BRONZE)
        msg = await ctx.send(embed=embed)

        async def load():
            bar = 0
            while bar < 10:
                await asyncio.sleep(0.4)
                bar += random.uniform(1, 4)
                if bar >= 9.5:
                    bar = 10.0
                    embed.title = "Waiting for results..."
                elif bar > 6:
                    embed.title = "Competing..."
                elif bar > 3:
                    embed.title = "Entering competitions..."
                embed.description = ("\u2588" * round(bar)) + (
                        "\u2591" * round(10 - bar) + " [" + str(round(bar * 10, 1)) + "%]")
                await msg.edit(embed=embed)

        async def update_medals():
            # Relative weights: 10, 7, 9, 9, 13, 14, 13, 9, 8, 6, 2
            medals_earned = random.choices([None, 6, 7, 8, 14, 15, 16, 17, 19, 20, random.randint(60, 80)],
                                           cum_weights=(10, 17, 26, 35, 48, 62, 75, 84, 92, 98, 100))[0]
            if medals_earned:
                user = self.bot.db().get(str(ctx.author_id))
                medals = medals_earned
                if user:
                    medals = medals_earned + user["medals"]
                    self.bot.db().update({"medals": medals}, str(ctx.author_id))
                else:
                    self.bot.db().insert({"medals": medals_earned}, key=str(ctx.author_id))
                nonlocal result
                result = ("WOOOOOOW!" if medals_earned > 59 else "Wow!") + " You won " + str(
                    medals_earned) + " :third_place:! You now have " + "{:,}".format(medals) + " :third_place:."

        result = "You won zero :third_place:. Better luck next time!"
        await asyncio.gather(load(), update_medals(), return_exceptions=True)
        embed.title = result
        await msg.edit(embed=embed)
```
I also pushed the branch to github: https://github.com/RealCyGuy/Bronze-Medalist/tree/override

**Comment by LordOfPolls** [comment]
Seems cooldowns don't work with cogs, I think I know the issue and will fix it when I have time

**Comment by RealCyGuy** [comment]
Alright 👍

**Comment by LordOfPolls** [comment]
That fixed it for me. While I was removing overrides for invoke, I accidentally left in a second `prepare` call which was causing cogs to always be on cooldown

**Comment by RealCyGuy** [comment]
Yes, it's working for me too. Thanks!

**Comment by LordOfPolls** [comment]
This was a bad idea, im closing this pr and going back to my previous solution of just adding in the required functionality instead of trying to inherit it

**Pull request closed without merging**
