### PR TITLE
Context menu example to README + indentation 4 spaces

### PR DESCRIPTION
**Pull request by Toricane**
## About this pull request

Adds a context menu example to the README.md, and changes the indentation of the example for the context menu in order for the examples' indentations to be consistent with each other.

## Changes

- README.md
- Getting Started docs

## Checklist

- [ ] I've run the `pre_push.py` script to format and lint code.
- [ ] I've checked this pull request runs on `Python 3.6.X`.
- [ ] This fixes something in [Issues](https://github.com/eunwoo1104/discord-py-slash-command/issues).
    - Issue:
- [ ] This adds something new.
- [ ] There is/are breaking change(s).
- [ ] (If required) Relevant documentation has been updated/added.
- [x] This is not a code change. (README, docs, etc.)

### CODE REVIEW

**Comment by i0bs** [comment]
Besides the indentation, what does this change? There's already an example of context menus [available here.](https://discord-py-slash-command.readthedocs.io/en/latest/gettingstarted.html#adding-context-menus)

**Comment by Toricane** [comment]
I added it on to the README.md, underneath the buttons and the selects

**Comment by i0bs** [comment]
I'm sorry, I'm a smooth brain.

**Review by i0bs — APPROVED** [review]

**Comment by i0bs** [comment]
Merging, thank you for contributing!

**Pull request merged**
