### PR TITLE
Implement context menus.

### PR DESCRIPTION
**Pull request by i0bs**
## About this pull request

This is an early attempt at implementing the context menus for the library.

## Changes

- Updated client.py
- Added create_context_menu in manage_components
- Created model for types

## Checklist

- [X] I've run the `pre_push.py` script to format and lint code.
- [X] I've checked this pull request runs on `Python 3.6.X`.
- [ ] This fixes something in [Issues](https://github.com/eunwoo1104/discord-py-slash-command/issues).
    - Issue:
- [X] This adds something new.
- [ ] There is/are breaking change(s).
- [X] (If required) Relevant documentation has been updated/added.
- [ ] This is not a code change. (README, docs, etc.)

### CODE REVIEW

**Comment by FayeDel** [comment]
As of this state, there's no cog_slash equivalent of adding `context=`.

**Comment by i0bs** [comment]
Investigated further. `to_dict` combing for showing the context menu commands is needed, as well as type data being passed.

**Comment by i0bs** [comment]
**NOTE**: I will be moving this PR to a ready-to-review state. I would like to note that this is still very WIP and there are a lot of things still being worked on. If you are experiencing any issues/bugs, please list them. Here is the current list of them that I am working on trying to fix:

- `sync_all_commands()` raises `APPLICATION_COMMAND_IMMUTABLE_TYPE` error: API backend-related issue that we will temporarily ignore for now.
- Subcommand registry gives back nesting error.
- Some slash commands may fail to fire due to invocation states being overlapped with the same slash command and context menu name.
- Some `MenuContext` instances may not be accessible for the time being due to `super()` registration affecting `SlashContext` instead of `InteractionContext` ... Which I am still not sure why?
- Tuple assignment for `cog_context_menu` causes indirect argument errors for instantiation of `CogBasecommandObject`
- **BREAKING/CRITICAL** Slash commands are not being invoked properly due to probable `on_socket_response` issue with interaction ID checks.
- **BREAKING/CRITICAL** Components are not functioning in favor of the new interaction ID types of context menus. Majorly responsible due to Discord, and once again, lack of documentation for new component interaction ID type.

__How do I test?__
You are able to test by using this line below:
`pip install -U git+https://github.com/goverfl0w/discord-py-interactions.git`

**Comment by i0bs** [comment]
All current bugs have been fixed, no critical bugs or issues have been found standing at this time after 8 strenuous test cycles. Waiting for checks completion.

**Pull request merged**
