### PR TITLE
Remove outdated note regarding ephemeral messages

### LINKED ISSUE #167: Ephemeral (hidden) Messages now support embeds
Whenever an embed is sent with the `hidden=True`, a warning is printed : `Embed/File is not supported for hidden!`. But ephemeral messages now support embeds.

### PR DESCRIPTION
**Pull request by anand2312**
## About this pull request

Updates docstring in `SlashContext.send` to remove an outdated note, regarding embeds in ephemeral messages.
Closes #167 

## Checklist

- [ ] I've checked this pull request runs on `Python 3.6.X`.
- [ ] This fixes something in [Issues](https://github.com/eunwoo1104/discord-py-slash-command/issues).
    - Issue:
- [ ] This adds something new.
- [ ] There is/are breaking change(s).
- [ ] (If required) Relevant documentation has been updated/added.
- [x] This is not a code change. (README, docs, etc.)

### CODE REVIEW

**Review by LordOfPolls — APPROVED** [review]

**Comment by quirky-bluejay** [comment]
The warning on send should also be removed

**Comment by anand2312** [comment]
> The warning on send should also be removed

preview This?

**Comment by quirky-bluejay** [comment]
I meant the code logger warming, but that too. And yeah that bit of code for sending files should be changed, if files are now supported.

**Comment by anand2312** [comment]
> I meant the code logger warming, but that too. And yeah that bit of code for sending files should be changed, if files are now supported.

I don't know if they are? I made this PR only because of a [discussion I saw in the server](https://discord.com/channels/789032594456576001/801461008865951784/838833181666574356), and am not familiar with this codebase
If you want me to make some more changes, can you point exactly which files / what needs to be done?

**Comment by quirky-bluejay** [comment]
If you'd like me to make those changes I'm happy to open another pr!

**Review by eunwoo1104 — APPROVED** [review]

**Comment by eunwoo1104** [comment]
Merging, thank you for contributing!

**Pull request merged**
