### PR TITLE
Create py.typed

### PR DESCRIPTION
**Pull request by ThatXliner**
## About this pull request

See https://discord.com/channels/789032594456576001/789032594456576004/829831919918645248

## Changes

Added a py.typed file

## Checklist

- [ ] I've checked this pull request runs on `Python 3.6.X`.
- [ ] This fixes something in [Issues](https://github.com/eunwoo1104/discord-py-slash-command/issues).
    - Issue:
- [X] This adds something new.
- [ ] There is/are breaking change(s).
- [ ] (If required) Relevant documentation has been updated/added.
- [X] This is not a code change. (README, docs, etc.)

### CODE REVIEW

**Review by LordOfPolls — APPROVED** [review]
Nothin much to it, this is fine, suggest merging

**Review by quirky-bluejay — CHANGES_REQUESTED** [review]
This shouldn't be merged until all code that is documented is correctly, and fully typed, which it is not currently.

**Comment by ThatXliner** [comment]
MyPy got a little bit more silent when I added this to the one in my venv. To make it stop whining a bit more, I had to add an `__all__` variable in the `__init__.py` of this library (in my venv).

**Comment by i0bs** [comment]
Keeping this PR open for revision, removing the wontfix label until there is a clearer consensus on this.

**Comment by LordOfPolls** [comment]
Closing due to inactivity

**Pull request closed without merging**
