### PR TITLE
Add functions to removes all commands.

### PR DESCRIPTION
**Pull request by 4surix**
Hello !  
  
I made two functions to delete all commands everywhere or just in one area (global or guild).  

### Why ?
I did this because I wanted to delete all the commands from a server and then put back only the ones I wanted, so that I could remove the ones that no longer exist and add the new ones.  
  
### Exemple :
```python
import discord
import discord_slash


bot = discord.Client()
slash = discord_slash.SlashCommand(bot)

@bot.event
async def on_ready(self):

    await slash.remove_all_commands()

    # Useless, because `remove_all_commands` already removes the global commands,
    #  just for the exemple.
    await slash.remove_all_commands_in('global')

    # As explained I then call up the existing `register_all_commands` function 
    #  to add the commands I want.
    await slash.register_all_commands()

bot.run(token)
```

Thank you for reading, have a nice day !

### CODE REVIEW

**Comment by eunwoo1104** [comment]
This is good function, but there are some questions.
1. This doesn't affect the SlashCommand itself. This should be in the `.utils.manage_commands`.
2. Why did you use `for x in self.commands.keys():`? This isn't necessary, and it is wasting some times.

**Comment by 4surix** [comment]
Actually as `register_all_commands` was in `SlashCommand`,  I thought it was the right place because `remove_all_commands` does the opposite of `register_all_commands`.  
  
Yes, `for x in self.commands.keys():` is absolutely useless here.  
I think I should go to sleep one day.

**Comment by eunwoo1104** [comment]
> Actually as `register_all_commands` was in `SlashCommand`, I thought it was the right place because `remove_all_commands` does the opposite of `register_all_commands`.

Well... `register_all_commands` reads commands registered in SlashCommand. However, yours read commands list from discord API. That's why I said this should be in the `.utils.manage_commands`.

**Comment by 4surix** [comment]
Okay I see, you are right,  
  
So I moved into `.utils.manage_commands` and this is what it looks like :

```python
import discord
import discord_slash
from discord_slash.utils import manage_commands


bot = discord.Client()
slash = discord_slash.SlashCommand(bot)

@bot.event
async def on_ready(self):
    await manage_commands.remove_all_commands(slash)
    await manage_commands.remove_all_commands_in(slash, 'global')
    await slash.register_all_commands()

bot.run(token)
```

It is good ? If yes, i commit this.

**Comment by eunwoo1104** [comment]
Looks good!

**Comment by eunwoo1104** [comment]
Merging this pull request. Thank you for contributing!
\+ I'll trim some code to fit the code style.

**Pull request merged**
