### PR TITLE
Refactoring entire extension

### PR DESCRIPTION
**Pull request by asleep-cult**

### CODE REVIEW

**Comment by eunwoo1104** [comment]
Wait, what?

**Comment by stellaurora** [comment]
hmm

**Comment by hpenney2** [comment]
I find this to a bit of an odd pull request as it's basically removing all of the existing code and adding your own. Why not just make your own extension if you're removing all of this extension's existing code? I don't really understand.

**Comment by eunwoo1104** [comment]
Closing this pull request, basically unnecessary.

**Comment by asleep-cult** [comment]
> I find this to a bit of an odd pull request as it's basically removing all of the existing code and adding your own. Why not just make your own extension if you're removing all of this extension's existing code? I don't really understand.

Good point... that's why I decided to only make a draft 🙂

**Comment by hpenney2** [comment]
Even if it's only a draft, it's still removing ***all*** of the existing code, at least from what I can see. A refactor doesn't seem necessary here in the main repository, however you might be able to create a new extension with your fork.

**Comment by TurnrDev** [comment]
This has my attention anyway. Since this is basically another project that does the same thing. What are the advantages of both versions? I've not started using any yet so I'm interested to find out.

**Comment by asleep-cult** [comment]
> This has my attention anyway. Since this is basically another project that does the same thing. What are the advantages of both versions? I've not started using any yet so I'm interested to find out.

Please dm me on discord `sleep-cult 🎄#3040` I'm sure discussion under this pr isn't wanted

**Pull request closed without merging**
