### PR TITLE
Implement PUT requests in auto_register

### PR DESCRIPTION
**Pull request by quirky-bluejay**
## About this pull request

This implements PUT requests for registering commands when `auto_register` and `auto_delete` are both true.
This will reduce the amount of requests made to discord, only one per guild/global compared to one request for each command for each scope.

## Changes 

- Added a `to_dict` to `SlashCommand` function to get all commands into a dictionary, this reduces duplicated code from `register_all_commands` and `sync_all_commands`
- Added `sync_all_commands` to `SlashCommand` which uses PUT requests to update the commands.
- Automatically call `sync_all_commands` when both `auto_register` and `auto_delete` are `True`
- Only call `register_all_commands` when `auto_register` is `True` and `auto_delete` isn't.
- Only call `delete_unused_commands` when `auto_register` is `True` and `auto_delete` isn't.
- Add `put_slash_commands` to http

## Checklist

- [x] I checked this pull request runs on `Python 3.6.X`.
- [ ] This fixes something in [Issues](https://github.com/eunwoo1104/discord-py-slash-command/issues).
    - Issue:
- [ ] This adds something new.
- [ ] There is/are breaking change(s).
- [x] (If required) Document string is updated/added.
- [ ] This changes anything except python code. (README, docs, etc.)

### CODE REVIEW

**Review by eunwoo1104 — CHANGES_REQUESTED** [review]
It looks like `to_dict` has `wait_until_ready`, but `register_all_commands` hasn't. This can be a problem if user just want to get a dict of the commands but can't use the coroutine. So we should also change the position of `wait_until_ready`.

**Comment by quirky-bluejay** [comment]
I decided to move `wait_until_ready` to `to_dict` because i thought that someone using it would want to make sure that all the commands are loaded.
If you think that the pros of not being an asyncronous functions outweigh that, i'll change it back.

**Comment by eunwoo1104** [comment]
> I decided to move `wait_until_ready` to `to_dict` because i thought that someone using it would want to make sure that all the commands are loaded.
> If you think that the pros of not being an asyncronous functions outweigh that, i'll change it back.

Ah, yeah you're right. I didn't think of that. I'll then accept this pull request, since anything else seems fine.

**Review by eunwoo1104 — APPROVED** [review]

**Comment by eunwoo1104** [comment]
Merging this pull request, thank you always for contributing!

**Pull request merged**
